All new tests in 'Bid' portion of Auction.js
Current output:
  Auction
    Bid - 60 points
      ✔ Should not allow the current maxBidder to bid again (+6 points) (501ms)
      ✔ Should fail if the value sent is not greater than the required minimum bid (+6 points)
      1) Should not allow bids if the auction has already ended (+6 points)
      ✔ Should not transfer any funds if bid is called the first time (+6 points)
      ✔ Should transfer funds if bid is called and conditions satisfied (+10 points)
      ✔ Should set minimumBid and maxBidder to new values after a bid (+6 points)
      ✔ Should instantly settle auction if a bid matches the max price (+8 points) (NEW)
      ✔ Should fail if the value sent doesn't meet the increment requirement (+6 points) (NEW)
      2) Should end the auction automatically when the time limit is reached (+6 points) (NEW)
      3) Should reject bids after the auction has ended (+6 points) (NEW)


  7 passing (533ms)
  3 failing

  1) Auction
       Bid - 60 points
         Should not allow bids if the auction has already ended (+6 points):
     Error: VM Exception while processing transaction: reverted with reason string 'Auction cannot be settled before end time.'
    at Auction.settleAuction (contracts/Marketplace.sol:58)
    at EdrProviderWrapper.request (node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:415:41)
    at HardhatEthersSigner.sendTransaction (node_modules/@nomicfoundation/hardhat-ethers/src/signers.ts:125:18)
    at send (node_modules/ethers/src.ts/contract/contract.ts:313:20)
    at Proxy.settleAuction (node_modules/ethers/src.ts/contract/contract.ts:352:16)
    at auctionEndedFixture (test/Auction.js:36:9)
    at loadFixture (node_modules/@nomicfoundation/hardhat-network-helpers/src/loadFixture.ts:59:18)
    at Context.<anonymous> (test/Auction.js:56:75)
  

  2) Auction
       Bid - 60 points
         Should end the auction automatically when the time limit is reached (+6 points):

      AssertionError: expected false to equal true
      + expected - actual

      -false
      +true
      
      at Context.<anonymous> (test/Auction.js:121:45)

  3) Auction
       Bid - 60 points
         Should reject bids after the auction has ended (+6 points):
     Error: VM Exception while processing transaction: reverted with reason string 'Auction cannot be settled before end time.'
    at Auction.settleAuction (contracts/Marketplace.sol:58)
    at EdrProviderWrapper.request (node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:415:41)
    at HardhatEthersSigner.sendTransaction (node_modules/@nomicfoundation/hardhat-ethers/src/signers.ts:125:18)
    at send (node_modules/ethers/src.ts/contract/contract.ts:313:20)
    at Proxy.settleAuction (node_modules/ethers/src.ts/contract/contract.ts:352:16)
    at auctionEndedFixture (test/Auction.js:36:9)
    at loadFixture (node_modules/@nomicfoundation/hardhat-network-helpers/src/loadFixture.ts:59:18)
    at Context.<anonymous> (test/Auction.js:126:76)